### ISSUE TITLE
Rear Truss Can Be Put On The Wrong Way

### ISSUE THREAD

**Issue by dboi88** [dboi88/CSI-Cargo-Freighter#2]
flip the attachment nodes on the freighter hull side so that it can only attach one way, this will stop the user putting it on upside 
http://forum.kerbalspaceprogram.com/index.php?/topic/155452-coyote-space-industries-cargo-freighter-beta-v01/&do=findComment&comment=3016312

**Comment by Urses** [comment]
Yes it was a fight. On trying to add the EVA truce i has the feeling that the truce showed allways the wrong way?

**Comment by dboi88** [comment]
Yeah unfortunately to preserve the COM points (which need to be really exact) i can't rotate the part in unity so that it appears the correct way when picked. Hopefully the new nodes will stop anyone putting in on incorrectly as the way it is now it'd be very difficult to get wrong.
http://i.imgur.com/x14KDz6.gif
