### ISSUE TITLE
Issues with CSI 

### ISSUE THREAD

**Issue by BararQ** [dboi88/CSI-Cargo-Freighter#55]
Hi dboi88,

I don't normally post but I made an account to post some issues I had with your mod since I enjoy using it. Not sure if you wanted it all in one or several post, but putting in just one.

CLS.cfg

This was referencing the wrong module [KolonyTools], it should be as shown below.

@PART[CSIfreighterRecycler]:NEEDS[KolonyTools]
{
	MODULE
	{

		name = ModuleKolonyTools
		passable = true
		surfaceAttachmentsPassable = false
		passableWhenSurfaceAttached = True
	}
}

@PART[CSIfreighterRecycler]:NEEDS[ConnectedLivingSpace]
{
	MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
		surfaceAttachmentsPassable = false
		passableWhenSurfaceAttached = True
	}
}

I could not find CSIfreightersmallrecycler, so it was added since it can crew 2 people.

@PART[CSIfreightersmallrecycler]:NEEDS[ConnectedLivingSpace]:HAS[!MODULE[ModuleConnectedLivingSpace]]
{
	MODULE
	{
		name = ModuleConnectedLivingSpace
		passable = true
		surfaceAttachmentsPassable = false
		passableWhenSurfaceAttached = True
	}
}

OSE.cfg
This was not showing up in game for me, looks like the opening { and closing } are missing. It works when I add them.

@PART[CSIfreighterWorkshop]:NEEDS[Workshop]
{
	MODULE
	{
		name = OseModuleWorkshop
		ProductivityFactor = 2.5 // How much units of the resource a processed per second
		UpkeepResource = ElectricCharge // This resource will be consumed 1 per second during processing
		MinimumCrew = 2 // Amount of Kerbals needed for the Workshop to work
		Animate = true
		UseSpecializationBonus = true
		ExperienceEffect = RepairSkill
		SpecialistEfficiencyFactor = 0.02
	}
	-
	-
	-
	
Skipped everything else 
	-
	-
	-
	-
	MODULE
	{
		name = OseModuleCategoryAddon
		Category = none
		IconPath = Squad/PartList/SimpleIcons/R&D_node_icon_robotics
	}
}	
	

KIS.cfg
SmallKISKontainer.cfg
The slot size was set to 100, which when it opens, it covers my entire screen and cuts out some parts. Set it to 50 in both files.

MKS.cfg 
I removed some stuff to shortin this up, It looks like the Mulch, Fertilizer and Supplies have the ratio messed up. Dont think its supposed to be 0.0.002, I changed it to 0.002

@PART[CSIfreighterSmallGreenhouse]:NEEDS[KolonyTools]
{
	
	MODULE
	{
		name = ModuleResourceConverter_USI
		ConverterName = Agroponics
		StartActionName = Start Agroponics
		StopActionName = Stop Agroponics
		
		UseSpecialistBonus = true
		SpecialistEfficiencyFactor = 0.2
		SpecialistBonusBase = 0.05
		ExperienceEffect = BotanySkill
		Efficiency = 1	
		
		INPUT_RESOURCE
		{
			ResourceName = Mulch
			Ratio =  0.0.00200000
		}
		INPUT_RESOURCE
		{
			ResourceName = Fertilizer
			Ratio =  0.0.00020000
		}
		OUTPUT_RESOURCE
		{
			ResourceName = Supplies
			Ratio = 0.0.00220000
			DumpExcess = False
		}
		INPUT_RESOURCE
		{
			ResourceName = ElectricCharge
			Ratio = 4.40
		}
		INPUT_RESOURCE
		{
			ResourceName = Machinery
			Ratio = 0.0000050
		}
		OUTPUT_RESOURCE
		{
			ResourceName = Recyclables
			Ratio = 0.0000050
			DumpExcess = true
		}
		REQUIRED_RESOURCE
		{
			ResourceName = Machinery
			Ratio = 250
		}
	}	

	
	
I did a complete fresh install of Kerbal 1.31 and used CKAN to install CSI. I get this spam error when I install the CSIfreightersciencelab and right click on it. It also fails to transmit research data. This same issue is on my 1.2.2 install. I just plopped the stock science station on the hull attachment points to get my science for now.

Exception handling event onPartActionUICreate in class ModuleScienceLab:System.NullReferenceException: Object reference not set to an instance of an object
  at ModuleScienceLab.updateModuleUI () [0x00000] in <filename unknown>:0 
  at ModuleScienceLab.onPartActionUI (.Part p) [0x00000] in <filename unknown>:0 
  at EventData`1[Part].Fire (.Part data) [0x00000] in <filename unknown>:0 
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

NullReferenceException: Object reference not set to an instance of an object
  at ModuleScienceLab.updateModuleUI () [0x00000] in <filename unknown>:0 
  at ModuleScienceLab.onPartActionUI (.Part p) [0x00000] in <filename unknown>:0 
  at EventData`1[Part].Fire (.Part data) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EventData`1:Fire(Part)
UIPartActionWindow:CreatePartList(Boolean)
UIPartActionWindow:UpdateWindow()
UIPartActionController:UpdateActiveWindows()
UIPartActionController:UpdateEditor()
UIPartActionController:Update()

Below is my current mod list.

"version": "2017.12.26.07.44.25",
	"identifier": "installed-default",
	"spec_version": "v1.6",
	"recommends": [
		{
			"name": "CargoFreighter"
		},
		{
			"name": "USI-LS"
		},
		{
			"name": "UKS"
		},
		{
			"name": "KIS"
		},
		{
			"name": "USITools"
		},
		{
			"name": "CommunityResourcePack"
		},
		{
			"name": "CommunityCategoryKit"
		},
		{
			"name": "FirespitterCore"
		},
		{
			"name": "USI-Core"
		},
		{
			"name": "Konstruction"
		},
		{
			"name": "GroundConstruction-Core"
		},
		{
			"name": "AT-Utils"
		},
		{
			"name": "ConfigurableContainers-Core"
		}

Just speaking to balance it seems the 5000EC - 1600kW cooling generator seems a bit high for me, compared to USI 3.75 Nuclear reactor with 4000EC - 5000kW cooling. Also found it was weird that you had the FillAmount = 0.95 in the file as it prevented me from maxing out my EC from the reactor.

 I wouldn't mind if you could consider another engine type that used LFO, or Liquid Fuel/EC combination since it takes a while for me to get a refueling station up and running for it. Karborundum is not cheap. For now I have it being used as a orbital refueling construction station above Kerbin until I can get the mining facilities up and running to use the engines in career mode.

Only ideas for modules I have at the moment would be CSI sized RCS thrusters,  Reaction wheels, Relay satellite, some supersized version of modules that fit in the large hanger space, and more attachment nodes on the hull and truss that I can attach stuff too.

I hope this helps and I really enjoy your mod.

**Comment by dboi88** [comment]
Hi, i really appreciate you taking the time to write all this up, i'm glad you like the mod. I will certainly look to fix all these issues at some point. 

It'd be great if you could split this up into separate issues so i can include them in the road map for future releases and allocate the tasks that'd be great, but don't worry if you can't spend the time, i will get around to it eventually.

I'm also open to Pull Requests if you wanted to submit the changes directly i'd be happy to merge them in.

Cheers

**Comment by BararQ** [comment]
Broke them out into individual issues, left the suggestions mostly in this thread as they are not an issue.

Back to upgrading my CSI space station. I actually have two of these stacked on each other, makes for a great low parts orbital storage,launch pad and refueling station.
