### ISSUE TITLE
Cargo truss joints weakened after reloading/time warp

### ISSUE THREAD

**Issue by GregBlow** [dboi88/CSI-Cargo-Freighter#6]
Presently a vessel configured Cockpit-hull + each EVA prep area -truss + 6 * 5m Kontainers - engines will perform appropriately after launching, however loses a great deal of structural integrity at both truss joints when reloading/exiting time warp/returning from tracking station. Physics time warp does not cause problems. Version 0.1.2. Some problem with reloading of physics that is not present on first load?

**Comment by dboi88** [comment]
I'll investigate this one tonight

**Comment by dboi88** [comment]
Fixed in next release
