### ISSUE TITLE
Probably needs a licence even in pre-release

### ISSUE THREAD

**Issue by GregBlow** [dboi88/CSI-Cargo-Freighter#7]
I'm not sure the present status of the mod allows for it to be linked from the forum without a licence, but I'm not an internet lawyer. Might want to check it.

http://forum.kerbalspaceprogram.com/index.php?/topic/41210-license-selection-guide/

**Comment by dboi88** [comment]
There is a licence on here, I've added it to the OP on the forum and added a copy into FOR RELEASE which i'll include in the next version, i think this covers all bases?

**Comment by GregBlow** [comment]
As far as I am aware, yes.

**Comment by dboi88** [comment]
Cheers
