### ISSUE TITLE
Small modules orientation abnormal

### ISSUE THREAD

**Issue by GregBlow** [dboi88/CSI-Cargo-Freighter#8]
0.1.5 - 0.1.7

Small greenhouse doesn't conform to natural orientation, off by -90 degrees around lateral axis when freshly dropped. 
- [x] Greenhouse Unity
- [x] Greenhouse KSP
- [x] HabCupola Unity
- [x] HabCupola KSP
- [x] Reactor Unity
- [x] Reactor KSP
- [x] Recycler Unity
- [x] Recycler KSP

**Comment by dboi88** [comment]
Fixed, will be included in 0.1.8
